hw08_envdir_tool
kermilov/2024-08-otus-go-ermilov pull request #8
Opened 2024-11-30 09:45 UTC by kermilov

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-12-01 07:34 UTC, vladislavmass requested changes

2024-12-01 07:34 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	return strings.TrimRight(value, " "), nil
Пробелы мы удалили, но по условию задания необходимо удалить еще и табуляции

2024-12-01 07:34 UTC, vladislavmass commented on hw08_envdir_tool/executor.go
> +	command.Env = env.ToEnv()
В список переменных среды должны попасть и переменные из папки и системные переменные за исключением удаленных. Сейчас же попадут только переменные из папки

2024-12-01 14:46 UTC, kermilov commented on hw08_envdir_tool/executor.go
> +	command.Env = env.ToEnv()
А у меня начитка из системных переменных зашита в создание экземпляра Environment, через New метод

2024-12-02 05:41 UTC, hungry-honeybadger commented on hw08_envdir_tool/executor.go
> +	command.Env = env.ToEnv()
Насчет решения с env не согласен, так как таким образом произошло фактически затачивание ридера под экзекьютер. То есть мы не должны в ридере знать как будут использоваться переменные. Например, для некой локальной утилиту нам есть смысл пробрасывать в нее переменные ос, а если  переменные нужны, что бы их выставить у cloud functions то ей наши переменные ос как минимум не нужны, а могут и пойти во вред.

2024-12-02 06:20 UTC, merged